# Generated by Django 4.2.13 on 2024-07-01 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BucketList",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(max_length=300, null=True)),
                ("is_succeed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bucket_list",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
