name: "✨ Feature"
description: "기능 구현해야 할 것이 있나요? 👀"
body:

  - type: textarea
    attributes:
      label: Describe
      description: |
        [Description] 구현할 작업을 작성해 주세요!
      placeholder: |
        ex) 로그인 기능 구현
  - type: textarea
    attributes:
      label: Additional
      description: |
        [추가사항] 별도로 알려줘야 할 사항이나 추가사항을 작성해주세요!