# Generated by Django 4.2.13 on 2024-08-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="device_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
