# Generated by Django 5.0.3 on 2024-04-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_socialprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="nickname"
            ),
        ),
    ]
