# Generated by Django 5.0.3 on 2024-04-03 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_nickname"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SocialProfile",
        ),
    ]
