# Generated by Django 5.0.3 on 2024-04-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_delete_socialprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_admin_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
