name: almaengi-cd

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install system dependencies (about docker)
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config
          sudo apt-get install -y mariadb-server python3-pip libmysqlclient-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make migrations
        run: |
          python manage.py makemigrations

      - name: Run migrations
        run: |
          python manage.py migrate
