name: Almeang-i-CI

on:
   pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        

    # test 명령어로 모든 app test
    - name: Run tests
      run: |
        python manage.py test

    - name: Lint code with flake8
      run: |
        pip install flake8
        flake8 .
