name: Almeang-i-CI

on:
   pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
   
    - name: Check if secrets.json exists
      run: |
        if [ -f secrets.json ]; then
          echo "secrets.json already exists. Skipping creation."
        else
          echo "secrets.json does not exist. Proceeding with JSON creation."
        fi

    - name: Create secrets.json
      id: create-json
      if: success() && !cancelled()
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "secrets.json"
        json: ${{ secrets.SECRET_JSON }}

        

    # test 명령어로 모든 app test
    - name: Run tests
      run: |
        python manage.py test

    - name: Lint code with flake8
      run: |
        pip install flake8
        flake8 .
