name: Almeang-i-CI

on:
   pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

   
    - name: Create secrets.json file if not exists
      run: |
        if [ ! -f GHJM/secrets.json ]; then
          echo "${{ secrets.SECRET_JSON }}" > GHJM/secrets.json
        else
          echo "secrets.json already exists. Skipping creation."
        fi     # endif

    - name: Verify secrets.json content
      run: |
        cat GHJM/secrets.json | python -m json.tool
        

    # test 명령어로 모든 app test
    - name: Run tests
      run: |
        python manage.py test

    - name: Lint code with flake8
      run: |
        pip install flake8
        flake8 .
